parameters:
#    base_guelek.example.class: Base\GuelekBundle\Example

services:
#    base_guelek.example:
#        class: %base_guelek.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
